version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - 85:80
    volumes:
      - ./src/:/var/www/html
      - ./logs/nginx:/var/log/nginx/
  php-env:
    image: php:fpm-alpine
    # build: .
    # container_name: php_docker_tutorial
    volumes:
      - ./src:/var/www/html
      - ./logs/php.log:/var/log/fpm-php.www.log
