version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: php_docker_tutorial_nginx
    ports: 
      - 86:80
    volumes:
      - ./src/:/var/www/html
      - ./logs/nginx:/var/log/nginx/
  php-env:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php_docker_tutorial
    volumes:
      - ./src:/var/www/html
      - ./logs/php.log:/var/log/fpm-php.www.log

  db:
    image: mysql
    container_name: php_docker_tutorial_mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3307:3306
